flags = ['-Wall',
         '-Wextra',
         '-Wc++98-compat',
         '-Wno-long-long',
         '-Wno-variadic-macros',
         '-fexceptions',
         '-fno-rtti',
         '-fno-strict-aliasing',
         '-fPIE',
         '-fpic',
         '-std=c++11',
         '-x', 'c++',
         '-I', '.']
