(require 'deft)
(setq deft-extensions '("org" "md"))
(setq deft-default-extension "org")
(setq deft-directory "~/Dropbox/org")
;; (setq deft-text-mode 'org-mode)
(setq deft-use-filename-as-title t)
(global-set-key (kbd "<f11>") 'deft)
(setq deft-auto-save-interval 20.0)
