;; Diminish modeline clutter
(require 'diminish)
;; (diminish 'wrap-region-mode)
(diminish 'yas-minor-mode " Y")
(diminish 'undo-tree-mode " UT")
;; (diminish 'guru-mode)
(diminish 'guide-key-mode)
;; (diminish 'magit-auto-revert-mode)
(diminish 'projectile-mode " P")
;; (diminish 'autopair-mode)
;; (diminish 'global-whitespace-mode)
(diminish 'git-gutter+-mode)
(diminish 'company-mode " C")
